---
title: "Reproducing figures in Cleveland's **Visualizing Data**"
author: "Shanti Agung"
date: "5/1/2020"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```


```{r, results='hide'}
library(tidyverse)
library(foreign)
library(RColorBrewer)
library(scales)
library(cowplot)

# load datasets
data.restore("visualizing_data.txt")
```

<br>

***

# **Chapter 1**   Introduction

<br>

```{r, warning=FALSE, fig.height=14, fig.width=5, fig.cap="**Figure 1.1**  A multiway dot plot graphs from a barley experiment run in the 1930s."}
ggplot(barley, aes(x=variety, y=yield, shape = year, color = year)) +
  geom_point() +
  coord_flip() +
  facet_wrap(vars(site), ncol=1) +
  scale_color_brewer(palette = "Set2") +
  theme(legend.position = "top") +
  labs(x="", y="Barley Yield (bushels/acre)")
```

<br><br>

```{r, fig.height=10, fig.width=5, fig.cap="**Fig 1.2**  Histograms garph the singer heigts by voice part. The interval width is one inch."}
ggplot(singer, aes(x=height)) +
  geom_histogram(bins = 16, 
                 aes(y = stat(width*density)),
                 fill = "#66C2A5",
                 color = "#66C2A5",
                 alpha = 0.8) +
  facet_wrap(vars(voice.part), ncol = 2) +
  scale_y_continuous(labels = percent_format(accuracy=1)) +
  labs(y="Percent of Total", x = "Height (inches)") +
  theme(panel.grid = element_blank())
```

<br><br>

```{r, out.width="70%", out.height="70%", fig.cap="**Figure 1.3**  An exploratory scatterplot graphs the Babinet point against particulate concentration."}
ggplot(polarization, aes(x = concentration, y = babinet)) +
  geom_point(color = "#FC8D62", fill = "#FC8D62", alpha = 0.4, size = 3) +
  labs(x = "Concentration (micrograms per cubic meter)", y = "Babinet Point (degrees)") +
  theme(panel.grid = element_blank())
```


<br><br>

```{r, out.width="70%", out.height="70%", fig.cap="**Figure 1.4**  Oxides of nitrogen are graphed against equivalent ratio."}
ggplot(ethanol, aes(x = E, y = NOx)) +
  geom_point(color = "#7570B3", fill = "#FC8D62", alpha = 0.3, size = 3) +
  labs(x = "E", y = "Oxides of nitrogen (micrograms/J)") +
  theme(panel.grid = element_blank())
```


<br><br>

```{r, out.width="70%", out.height="70%", fig.cap="**Figure 1.5**  Oxides of nitrogen are graphed against compression ratio."}
ggplot(ethanol, aes(x = C, y = NOx)) +
  geom_point(color = "#7570B3", fill = "#FC8D62", alpha = 0.3, size = 3) +
  labs(x = "C", y = "Oxides of nitrogen (micrograms/J)") +
  theme(panel.grid = element_blank())
```

<br><br>

```{r, fig.height= 15, fig.width= 5, fig.cap="**Figure 1.6**  The barley data are graphed by a multiway dot plot with the data for each site on two panels, one for 1931 and one for 1932."}
ggplot(barley, aes(x=variety, y=yield)) +
  geom_point(color = "#66C2A5") +
  coord_flip()+
  facet_wrap(vars(site,year), ncol=2) +
  labs(y="Barley Yield (bushels/acre)", x="")
```

<br>

***

# **Chapter 2**   Univariate Data

<br>


```{r, fig.height= 10, fig.width= 5, fig.cap="**Figure 2.1**  Quantile plots display univariate data: the heights of singers in the New York Choral Society" }
ggplot(singer, aes(sample=height)) +
  geom_qq(distribution = qunif, color = "#FC8D62") +
  facet_wrap(vars(voice.part), ncol = 2, as.table = FALSE) +
  labs(x = "f-value", y = "Height (inches)") +
  scale_x_continuous(breaks = c(0.0, 0.5, 1.0))
```

<br><br>


```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.2**   The symbols and the line segments show the quantile function of the first tenor heights"}

make_qq <- function(dd, x) {
  dd<-dd[order(dd[[x]]), ]
  dd$qq <- qunif(ppoints(nrow(dd)))
  dd
}

ggplot(make_qq(singer[singer$voice.part=="Tenor 1", ], "height"),
       aes(x=qq, y=height)) + 
  geom_line(color = "#FC8D62") +
  geom_point(size=3, color="#FC8D62", fill="white", shape=21, stroke=1) + 
  labs(x="f-value",y="Tenor 1 Height (inches)") +
  theme(legend.position = "none",
        panel.grid.minor = element_blank())
```


<br><br>


```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.3** The first tenor and second bass height distributions are compared by a q-q plot"}

singer_qq <- singer %>%
  group_by(voice.part) %>%
  arrange(height) %>%
  mutate(fval = (row_number() - 0.5)/n()) %>%
  ungroup()

data_bass <- singer_qq %>% filter(voice.part == "Bass 2")
data_tenor <- singer_qq %>% filter(voice.part == "Tenor 1")
bass_height_interpolate <- approx(data_bass$fval,  data_bass$height, data_tenor$fval)

data_tenor %>%
  mutate(bass_2 = bass_height_interpolate$y) %>%
  rename(tenor_1 = height) %>%
  select(fval, tenor_1, bass_2) %>%
  ggplot(aes(x=tenor_1, y=bass_2)) +
  geom_point(size=3, color="#FC8D62", fill="white", shape=21, stroke=1) +
  geom_abline(intercept = 0, slope = 1, color="#D95F02" ) +
  scale_x_continuous(limits = c(64,76)) +
  scale_y_continuous(limits = c(64,76)) +
  labs(x = "Tenor 1 Height (inches)",
       y = "Bass 2 Height (inches)") +
  theme(panel.grid = element_blank())
```

<br><br>




```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.4** The first tenor and second bass height distributions are compared by a Tukey m-d plot"}
matched_tenor_bass <- data_tenor %>%
  mutate(bass_2 = bass_height_interpolate$y) %>%
  rename(tenor_1 = height) %>%
  select(fval, tenor_1, bass_2)

matched_tenor_bass %>%
  mutate(diff = bass_2 - tenor_1, mean = (bass_2 + tenor_1)/2) %>%
  ggplot(aes(x=mean, y=diff)) +
  geom_point(color="#FC8D62", size = 2) +
  geom_hline(yintercept = 0, color="#D95F02") +
  labs(x="Difference (inches)", y="Mean (inches)") +
  scale_x_continuous(breaks = seq(66,76,2)) +
  theme(panel.grid = element_blank())
```


<br><br>

```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.8** The eight singer distribution are compared by box plots"}
ggplot(singer, aes(x=voice.part, y=height)) +
  geom_boxplot(fill=alpha("#FC8D62", 0.4), color="#D95F02") +
  coord_flip() +
  labs(x = "", y="Height (inches)") +
  theme(panel.grid = element_blank()) 
```

<br><br>


```{r fig.height= 10, fig.width= 5, fig.cap="**Figure 2.11**  Normal q-q plots compare the eight height distributions with the normal distribution" }
ggplot(singer, aes(sample=height)) +
  geom_qq(color="#FC8D62") +
  stat_qq_line(color="#666666") +
  facet_wrap(vars(voice.part), ncol = 2, as.table = FALSE) +
  labs(x="Unit Normal Quantile", y="Height (inches)") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())

```

<br><br>


```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.12** A dot plot displays the sample means of the height distributions"}
singer %>%
  group_by(voice.part) %>%
  summarise(mean_height = mean(height)) %>%
  ggplot(aes(x=voice.part, y=mean_height)) +
  geom_point(color="#FC8D62", size = 3) +
  coord_flip() +
  labs(y="Mean Height (inches)", x ="") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted"))
```

<br><br>



```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.13** Box plots compare the distributions of the height residuals for the fit to the data by voice-part means"}

singer_fitted <- singer %>%
  group_by(voice.part) %>%
  mutate(mean_height = mean(height),
         residual_height = height - mean_height) %>%
  ungroup()

singer_fitted %>%
  ggplot(aes(x=voice.part, y=residual_height)) +
  geom_boxplot(fill=alpha("#FC8D62", 0.4), color="#D95F02") +
  coord_flip() +
  geom_hline(yintercept = 0, color="#666666") +
  labs(x="", y="Residual Height (inches)") +
  theme(panel.grid = element_blank()) +
  scale_y_continuous(limits = c(-6,7.5), breaks = c(-6,-2,2,6))
```

<br><br>



```{r, fig.height= 10, fig.width= 5, fig.cap="**Figure 2.14**  Each panel is a q-q plot that compares the distribution of the residuals for one voice part with the distribution of the pooled residuals"}

singer_res_pooled <- singer_fitted %>%
  group_by(voice.part) %>%
  arrange(residual_height) %>%
  mutate(fval = (row_number() - 0.5)/ n()) %>%
  ungroup() %>%
  mutate(residual_pooled = quantile(residual_height, probs = fval)) %>%
  select(fval, residual_height, residual_pooled, voice.part)

ggplot(singer_res_pooled, aes(x=residual_pooled, y=residual_height)) +
  geom_point(color="#FC8D62") +
  geom_abline(intercept = 0, slope = 1, color="#666666") +
  facet_wrap(vars(voice.part), ncol=2, as.table = FALSE) +
  labs(x="Residual Height (inches)", y="Residual Height (inches)") +
  scale_x_continuous(breaks = c(-4,0,4)) +
  scale_y_continuous(breaks = c(-4,0,4)) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())
```

<br><br>


```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.15** The pooled residuals are displayed by a quantile plot"}
ggplot(singer_res_pooled, aes(sample = residual_height)) +
  geom_qq(distribution = qunif, color="#FC8D62", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Residual Height (inches)") +
  theme(panel.grid = element_blank()) +
  scale_y_continuous(limits = c(-6,7.5), breaks = c(-6, -2, 2, 6))


quantile_0.025 <- quantile(singer_fitted$residual_height, probs = 0.025, type = 5)
quantile_0.975 <- quantile(singer_fitted$residual_height, probs = 0.975, type = 5)

var_residuals_pooled <- abs((quantile_0.975 - quantile_0.025)/2)

mean_soprano_1 <- mean(singer$height[singer$voice.part == "Soprano 1"])
lowerb_soprano_1 <- mean_soprano_1 - var_residuals_pooled
upperb_soprano_1 <- mean_soprano_1 + var_residuals_pooled

```

<br><br>



```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.16** A normal q-q plot compares the distribution of the pooled residuals with a normal distribution"}
ggplot(singer_fitted, aes(sample = residual_height)) +
  geom_qq(color="#FC8D62", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color="#666666") +
  labs(x = "Unit Normal Quantile", y = "Residual Height (inches)") +
  scale_y_continuous(breaks = c(-6, -2, 2, 6)) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r, fig-sub, fig.cap='**Figure 2.17** An r-f spread plot compares the spreads of the residuals and the fitted values minus their mean for the fit to the singer data',  fig.subcap=c('', ''), out.width='50%', fig.asp=1, fig.ncol = 2}

ggplot(singer_fitted, aes(sample = (mean_height - mean(mean_height)))) +
  geom_qq(distribution = qunif, color="#FC8D62", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Height (inches)") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(limits = c(-6,7.5), breaks = c(-6, -2, 2, 6))

ggplot(singer_fitted, aes(sample = residual_height)) +
  geom_qq(distribution = qunif, color="#FC8D62", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Residual Height (inches)") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(limits = c(-6,7.5), breaks = c(-6, -2, 2, 6))

```

<br><br>


```{r, fig.cap="**Figure 2.19** Quantile plots display the two distributions of the fusion-time data"}
ggplot(fusion.time, aes(sample = time)) +
  geom_qq(distribution = qunif, color="#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Time (seconds)") +
  facet_wrap(vars(nv.vv)) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank()) 
```

<br><br>



```{r, fig.cap="**Figure 2.22** Normal q-q plots compare the distributions of the fusion-time data with the normal distribution"}
ggplot(fusion.time, aes(sample = time)) +
  geom_qq(color = "#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color="#666666") +
  facet_wrap(vars(nv.vv)) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(x="Unit Normal Quantile", y="Time (seconds)")
```

<br><br>




```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.23** The distributions of the fusion times are compared by box plots"}
ggplot(fusion.time, aes(x=nv.vv, y=time)) +
  geom_boxplot(fill=alpha("#8DA0CB", 0.5), color="#7570B3") +
  coord_flip() +
  theme(panel.grid = element_blank()) +
  labs(x="", y="Time (seconds)")
```

<br><br>



```{r, fig.cap="**Figure 2.24** Normal q-q plots compare the distributions of the log fusion times with the normal distribution"}
ggplot(fusion.time, aes(sample = log2(time))) +
  geom_qq(color = "#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color="#666666") +
  facet_wrap(vars(nv.vv)) +
  labs(x="Unit Normal Quantile", 
       y=expression(paste("Log Time (", log[2], " seconds)"))) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank()) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4, 5))
```

<br><br>



```{r, out.width = "70%", out.height="70%", fig.cap="**Figure 2.25** The s-l plot for the fusion times checks for nonuniform spread"}

fusion_mads <- fusion.time %>%
  group_by(nv.vv) %>%
  mutate(median = median(time), residual = abs(time - median),
         log_time = log2(time), 
         median_log = median(log_time), residual_log = abs(log_time - median_log)) 

ggplot(fusion_mads, aes(x=median, y=sqrt(residual))) +
  geom_jitter(color = "#8DA0CB", size = 2.5, fill=alpha("#8DA0CB", 0.3), shape=21, stroke=1,
              width = 0.2, height = 0.2) +
  stat_summary(fun.y = median, geom = "line", col = "#7570B3") +
  labs(x="Jittered Median Time (seconds)", 
       y=expression(paste("Square Root Absolute Residual Time (", seconds^{1/2},")"))) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r, out.width = "70%", out.height="70%", fig.cap="**Figure 2.26** The s-l plot for the log fusion times checks for nonuniform spread"}
ggplot(fusion_mads, aes(x=median_log, y=sqrt(residual_log))) +
  geom_jitter(color = "#8DA0CB", size = 2.5, fill=alpha("#8DA0CB", 0.3), shape=21, stroke=1,
              width = 0.1, height = 0.1) +
  stat_summary(fun.y = median, geom = "line", col = "#7570B3") +
  labs(x=expression(paste("Jittered Median Log Time (", log[2], " seconds)")), 
       y=expression(paste("Square Root Absolute Residual Log Time ( | ", log[2], " ", seconds^{1/2}, " | )"))) +
  theme(panel.grid = element_blank())
```


<br><br>


```{r,out.width="70%", out.height="70%", fig.cap="**Figure 2.27** The q-q plot compares the distributions of the fusion times"}
fusion_qq <- fusion.time %>%
  group_by(nv.vv) %>%
  arrange(time) %>%
  mutate(fval = (row_number() - 0.5)/n()) %>%
  ungroup()

data_nv <- fusion_qq %>% filter(nv.vv == "NV")
data_vv <- fusion_qq %>% filter(nv.vv == "VV")
nv_time_interpolate <- approx(data_nv$fval,  data_nv$time, data_vv$fval)

nvvv_qq <- data_vv %>%
  mutate(nv = nv_time_interpolate$y) %>%
  rename(vv = time) %>%
  select(fval, vv, nv) 

nvvv_qq %>%
  ggplot(aes(x=nv, y=vv)) +
  geom_point(color = "#8DA0CB", size = 3, fill="white", shape=21, stroke=1) +
  geom_abline(intercept = 0, slope = 1, color="#7570B3" ) +
  scale_x_continuous(limits = c(0,45)) +
  scale_y_continuous(limits = c(0,45)) +
  labs(x = "NV Time (seconds)",
       y = "VV Time (seconds)") +
  theme(panel.grid = element_blank())
```


<br><br>


```{r out.width="70%", out.height="70%%", fig.cap="**Figure 2.28** The q-q plot compares the distributions of the log fusion times"}

nvvv_qq %>%
  mutate(log_nv = log2(nv), log_vv = log2(vv)) %>%
  ggplot(aes(x=log_nv, y=log_vv)) +
  geom_point(color = "#8DA0CB", size = 3, fill="white", shape=21, stroke=1) +
  geom_abline(intercept = 0, slope = 1, color="#7570B3" ) +
  scale_x_continuous(limits = c(0,5.5), breaks = c(0, 1, 2, 3, 4, 5)) +
  scale_y_continuous(limits = c(0,5.5), breaks = c(0, 1, 2, 3, 4, 5)) +
  labs(x = expression(paste("Log NV Time (", log[2], " seconds)")),
       y = expression(paste("Log VV Time (", log[2], " seconds)"))) +
  theme(panel.grid = element_blank())



```

<br><br>

```{r out.width="70%", out.height="70%%", fig.cap="**Figure 2.29** The m-d plot provides more information about the shift of the log fusion times"}
nvvv_qq %>%
  mutate(log_nv = log2(nv), log_vv = log2(vv),
         diff = log_vv - log_nv, mean = (log_nv + log_vv)/2) %>%
  ggplot(aes(x=mean, y=diff)) +
  geom_point(color="#8DA0CB", size = 2) +
  geom_hline(yintercept = 0, color="#7570B3") +
  labs(x=expression(paste("Difference (", log[2], " seconds)")), 
       y=expression(paste("Mean (", log[2], " seconds)"))) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r, fig.cap="**Figure 2.30** Each panel is a q-q plot that compares the distribution of the residuals for one group of log times with the distribution of the pooled residuals."}

fusion_fitted <- fusion.time %>%
  mutate(log_time = log2(time)) %>%
  group_by(nv.vv) %>%
  mutate(mean_ltime = mean(log_time),
         residual_ltime = log_time - mean_ltime) %>%
  ungroup()

fusion_res_pooled <- fusion_fitted %>%
  group_by(nv.vv) %>%
  arrange(log_time) %>%
  mutate(fval = (row_number() - 0.5)/n()) %>%
  ungroup() %>%
  mutate(residual_pooled = quantile(residual_ltime, probs = fval)) %>%
  select(fval, residual_ltime, residual_pooled, nv.vv)

ggplot(fusion_res_pooled, aes(x=residual_pooled, y=residual_ltime)) +
  geom_point(color="#8DA0CB") +
  geom_abline(intercept = 0, slope = 1, color="#666666") +
  facet_wrap(vars(nv.vv)) +
  labs(x=expression(paste("Residual Log Time (", log[2], " seconds)")), 
       y=expression(paste("Residual Log Time (", log[2], " seconds)"))) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())
```


<br><br>

```{r, out.width="70%", out.height="70%%", fig.cap="**Figure 2.31** A normal q-q plot compares the normal distribution with the distribution of the pooled residuals for the fit to log fusion time"}
ggplot(fusion_res_pooled, aes(sample = residual_pooled)) +
  geom_qq(color="#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color="#666666") +
  labs(x = "Unit Normal Quantile", 
       y = expression(paste("Residual Log Time (", log[2], " seconds)"))) +
  scale_y_continuous(breaks = c(-2,-1, 0, 1, 2, 3)) +
  theme(panel.grid = element_blank())
```

<br><br>

```{r, out.width='50%', fig.subcap=c('', ''), fig.asp=1, fig.ncol = 2, fig.cap="**Figure 2.32** An r-f spread plot compares the spreads of the residuals and the fitted values minus their mean for the fit to log fusion time"}

ggplot(fusion_fitted, aes(sample = (mean_ltime - mean(mean_ltime)))) +
  geom_qq(distribution = qunif, color="#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", 
       y= expression(paste("Log Time (",log[2], " seconds)"))) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(limits = c(-2,3), breaks = c(-2,-1, 0, 1, 2, 3))

ggplot(fusion_fitted, aes(sample = residual_ltime)) +
  geom_qq(distribution = qunif, color="#8DA0CB", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Log Time (log2 seconds)") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(breaks = c(-2,-1, 0, 1, 2, 3))


```

<br><br>



```{r fig.height= 10, fig.width= 5, fig.cap="**Figure 2.33** Seven power transformations of the VV times are displayed by normal q-q plots"}

power_transformation <- function(x, p=0) {
  if (p != 0) {
    z <- x^p
  }
  else {
    z <- log2(x)
  }
  return(z)
}

add_pwr_tag <- function(x, tag) {
  z <- x %>%
    mutate(p = tag)
  return(z)
}

vv_time <- fusion.time %>%
  filter(nv.vv == "VV") %>%
  select(time)

tau <- c(1.00, 0.50, 0.25, 0.00, -0.25, -0.50, -1.00)
vv_transformed <- NULL

for (i in tau) {
  vv_tmp <- add_pwr_tag(power_transformation(vv_time, i), i)
  vv_transformed <- bind_rows(vv_transformed, vv_tmp)
}

ggplot(vv_transformed, aes(sample = time)) +
  geom_qq(color="#8DA0CB") +
  stat_qq_line(color="#666666") +
  labs(x = "Unit Normal Quantile", y = "VV Time") +
  facet_wrap(vars(p), scales = "free_y", ncol = 2, as.table = FALSE) +
  theme(panel.grid.minor.y=element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank())
```

<br><br>



```{r fig.height= 10, fig.width= 3, fig.cap="**Figure 2.34** Quantile plots display the chain length measurements for three ecosystem dimensions"}
ggplot(food.web, aes(sample = mean.length)) +
  geom_qq(distribution = qunif, color = "#66C2A5") +
  labs(x="f-value", y="Chain Length") +
  facet_wrap(vars(dimension), ncol = 1, as.table = FALSE) +
  scale_x_continuous(breaks = c(0.0, 0.5, 1)) +
  theme(panel.grid.minor.y = element_blank())
```

<br><br>



```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.35** The s-l plot for the chain lengths checks for nonuniform spread"}

foodweb_mads <- food.web %>%
  group_by(dimension) %>%
  mutate(median = median(mean.length), residual = abs(mean.length - median),
         log_mlength = log2(mean.length),
         median_log = median(log_mlength), residual_log = abs(log_mlength - median_log),
         invrs_mlength = (mean.length)^(-1),
         median_invrs = median(invrs_mlength), residual_invrs = abs(invrs_mlength - median_invrs)
         ) %>%
  ungroup()

ggplot(foodweb_mads, aes(x = median, y= sqrt(residual))) +
  geom_jitter(color = "#66C2A5", size = 2.5, fill=alpha("#66C2A5", 0.3), shape=21, stroke=1,
              width = 0.05, height = 0.05) +
  stat_summary(fun.y = median, geom = "line", color = "#1B9E77") +
  labs(x="Jittered Median Chain Length", y="Square Root Absolute Residual Chain Length") +
  scale_x_continuous(breaks = c(2.4, 2.6, 2.8, 3.0, 3.2)) +
  theme(panel.grid = element_blank())
```


<br><br>

```{r fig.height= 9, fig.width= 3, fig.cap="**Figure 2.36** Normal q-q plots compare the chain length distributions with the normal distribution" }
ggplot(food.web, aes(sample = mean.length)) +
  geom_qq(color = "#66C2A5") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile", y = "Chain Length") +
  facet_wrap(vars(dimension), ncol = 1, as.table = FALSE) +
  scale_y_continuous(breaks = c(2, 3, 4, 5, 6)) +
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())
```

<br><br>



```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.37** The s-l plot for the log chain lengths checks for nonuniform spread"}

ggplot(foodweb_mads, aes(x = median_log, y=sqrt(residual_log))) +
  geom_jitter(color = "#66C2A5", size = 2.5, fill=alpha("#66C2A5", 0.3), shape=21, stroke=1,
              width = 0.03, height = 0.03) +
  stat_summary(fun.y = median, geom = "line", color = "#1B9E77") +
  labs(x=expression(paste("Jittered Median ", Log[2], " Chain Length")), 
       y=expression(paste("Square Root Absolute Residual ", Log[2]," Chain Length"))) +
  scale_x_continuous(breaks = c(1.3, 1.4, 1.5, 1.6, 1.7)) +
  scale_y_continuous(breaks = c(0.0, 0.2, 0.4, 0.6, 0.8)) +
  theme(panel.grid = element_blank())
```

<br><br>

```{r fig.height= 9, fig.width= 3, fig.cap="**Figure 2.38** Normal q-q plots compare the log chain length distributions with the normal distribution"}
ggplot(foodweb_mads, aes(sample = log_mlength)) +
  geom_qq(color = "#66C2A5") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile",
       y = expression(paste(Log[2], " Chain Length"))) +
  facet_wrap(vars(dimension), ncol = 1, as.table = FALSE) +
  scale_y_continuous(breaks = c(1.0, 1.5, 2.0, 2.5)) +
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())
```

<br><br>



```{r fig.height= 10, fig.width= 5, fig.cap="**Figure D-2.38** Seven power transformations of the Mixed dimension's chain length are displayed by normal q-q plots"}

chain_mixed <- food.web %>%
  filter(dimension == "Mixed") %>%
  select(mean.length)

gen_multi_transform <- function(original_values, tau_list) {
  transformed_values <- NULL
  for (i in tau_list) {
    tmp_values <- add_pwr_tag(power_transformation(original_values, i), i)
    transformed_values <- bind_rows(transformed_values, tmp_values)
  }
  return(transformed_values)
}


chain_mixed_transformed <- gen_multi_transform(chain_mixed, tau)


ggplot(chain_mixed_transformed, aes(sample = mean.length)) +
  geom_qq(color = "#66C2A5") +
  stat_qq_line(color="#666666") +
  labs(x = "Unit Normal Quantile", y = "Chain Length of Mixed Dimension") +
  facet_wrap(vars(p), scales = "free_y", ncol = 2, as.table = FALSE) +
  theme(panel.grid.minor.y=element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank())
```

<br><br>


```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.39** The s-l plot for the inverse chain lengths, or link fractions, checks for nonuniform spread"}
ggplot(foodweb_mads, aes(x = median_invrs, y= sqrt(residual_invrs))) +
  geom_jitter(color = "#66C2A5", size = 2.5, fill=alpha("#66C2A5", 0.3), shape=21, stroke=1,
              width = 0.01, height = 0.01) +
  stat_summary(fun.y = median, geom = "line", color = "#1B9E77") +
  labs(x="Jittered Median Link Fraction", y="Square Root Absolute Residual Chain Length") +
  scale_x_continuous(breaks = c(0.30, 0.34, 0.38, 0.42)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r fig.height= 8, fig.width= 3, fig.cap="**Figure 2.40** Normal q-q plots compare the distributions of link fractions with the normal distribution"}

ggplot(foodweb_mads, aes(sample = invrs_mlength)) +
  geom_qq(color = "#66C2A5") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile",
       y = "Link Fraction") +
  facet_wrap(vars(dimension), ncol = 1, as.table = FALSE) +
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())
```

<br><br>



```{r fig.height= 8, fig.width= 3, fig.cap="**Figure 2.41** Each panel is a q-q plot that compares the distribution of the residuals for one group of link fractions with the distribution of te pooled residuals"}

foodweb_fitted <- food.web %>%
  mutate(invrs_mlength = mean.length^(-1)) %>%
  group_by(dimension) %>%
  mutate(mean_link_frac= mean(invrs_mlength),
         residual_link_frac = invrs_mlength - mean_link_frac) %>%
  ungroup()


foodweb_res_pooled <- foodweb_fitted %>%
  group_by(dimension) %>%
  arrange(invrs_mlength) %>%
  mutate(fval = (row_number() - 0.5)/n()) %>%
  ungroup() %>%
  mutate(residual_pooled = quantile(residual_link_frac, probs = fval)) %>%
  select(fval, residual_link_frac, residual_pooled, dimension)


ggplot(foodweb_res_pooled, aes(x=residual_pooled, y= residual_link_frac)) +
  geom_point(color = "#66C2A5") +
  geom_abline(intercept = 0, slope = 1, color = "#666666") +
  labs(x = "Residual Link Fraction", y="Residual Link Fraction") +
  facet_wrap(vars(dimension), ncol = 1, as.table = FALSE) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())
```

<br><br>



```{r out.width='50%', fig.subcap=c('', ''), fig.asp=1, fig.ncol = 2, fig.cap="**Figure 2.42** An r-f spread plot compares the spreads of the residuals and the fitted values minus their mean for the fit to the link fraction"}

ggplot(foodweb_fitted, aes(sample = (mean_link_frac - mean(mean_link_frac)))) +
  geom_qq(distribution = qunif, color="#66C2A5", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Link Fraction") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(limits = c(-0.16, 0.25), breaks = c(-0.1, 0.0, 0.1, 0.2))

ggplot(foodweb_fitted, aes(sample = residual_link_frac)) +
  geom_qq(distribution = qunif, color="#66C2A5", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "f-value", y="Link Fraction") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(limits = c(-0.16, 0.25), breaks = c(-0.1, 0.0, 0.1, 0.2))
```

<br><br>



```{r, out.width="70%", out.height="70%", fig.cap="**Figure 2.43** Box plots compare the distributions of the bin packing data"}
ggplot(bin.packing, aes(x = as.factor(number.runs), y = log2(empty.space))) +
  geom_boxplot(fill=alpha("#E78AC3", 0.5), color = "#E7298A") +
  coord_flip() +
  labs(x = "", y = expression(paste(Log[2], " Empty Space"))) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r out.width="70%", out.height="70%", fig.cap="**Figure D-2.43** Violin plots compare the distributions of the bin packing data"}
ggplot(bin.packing, aes(x = as.factor(number.runs), y = log2(empty.space))) +
  geom_violin(fill=alpha("#E78AC3", 0.5), color = "#E7298A") +
  coord_flip() +
  labs(x = "", y = expression(paste(Log[2], " Empty Space"))) +
  theme(panel.grid = element_blank())
```
 
<br><br>
 


```{r fig.height= 10, fig.width= 8, fig.cap="**Figure 2.44** Normal q-q plots compare the distributions of the bin packing data with the normal distribution"}
ggplot(bin.packing, aes(sample = log2(empty.space))) +
  geom_qq(color = "#E78AC3") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile", 
       y= expression(paste(Log[2], " Empty Space"))) +
  facet_wrap(vars(number.runs), ncol = 3, as.table = FALSE) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())
```

<br><br>



```{r fig.height= 10, fig.width= 8, fig.cap="**Figure 2.45** Normal q-q plots display spread-standardized residuals from the robust fit to the bin packing data"}

binpack_mads <- bin.packing %>%
  mutate(log_empty_space = log2(empty.space)) %>%
  group_by(number.runs) %>%
  mutate(median = median(log_empty_space),
         residual = log_empty_space - median,
         abs_residual = abs(residual),
         mads = median(abs_residual),
         spread_std_res = residual/mads) %>%
  ungroup()

ggplot(binpack_mads, aes(sample = spread_std_res)) +
  geom_qq(color = "#E78AC3") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile", 
       y= expression(paste("Spread-Standardized Residual ", Log[2], " Empty Space"))) +
  facet_wrap(vars(number.runs), ncol = 3, as.table = FALSE) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())

```

<br><br>



```{r fig.height= 10, fig.width= 5, fig.cap="**Figure 2.46** The q-q plots compare distributions of spread-standardized residuals for seven values of *n* with the pooled values of the seven distributions"}
binpack_res_pooled <- binpack_mads %>%
  filter(number.runs > 1000) %>%
  group_by(number.runs) %>%
  arrange(log_empty_space) %>%
  mutate(fval = (row_number() - 0.5)/n()) %>%
  ungroup() %>%
  mutate(spread_std_res_pooled = quantile(spread_std_res, probs = fval)) %>%
  select(fval, spread_std_res, spread_std_res_pooled, number.runs)

ggplot(binpack_res_pooled, aes(x=spread_std_res_pooled, y=spread_std_res)) +
  geom_point(color = "#E78AC3") +
  geom_abline(intercept = 0, slope = 1, color = "#666666") +
  labs(x = expression(paste("Spread-Standardized Residual ", Log[2], " Empty Space")), 
       y= expression(paste("Spread-Standardized Residual ", Log[2], " Empty Space"))) +
  facet_wrap(vars(number.runs), ncol = 2, as.table = FALSE) +
  scale_y_continuous(breaks = c(-4,0,4), limits = c(-4.1, 4.1)) +
  scale_x_continuous(breaks = c(-4,-0, 4), limits = c(-4.1, 4.1))

```

<br><br>



```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.47** The normal q-q plot compares the normal distribution with the distribution of te pooled spread-standardized residuals for seven values of *n*"}
binpack_mads %>%
  filter(number.runs > 1000) %>%
  ggplot(aes(sample = spread_std_res)) +
  geom_qq(color="#E78AC3", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile",
    y = expression(paste("Spread-Standardized Residual ", Log[2], " Empty Space"))) +
  scale_y_continuous(breaks = c(-4,-2,0,2,4)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.48** Median log empty space is graphed against log number of weights"}

binpack_mads_log <- binpack_mads %>%
  mutate(log_num_runs = log2(number.runs),
         log_mads = log2(mads),
         min_mads = min(mads),
         relative_mads = log2(mads/min_mads)) %>%
  distinct(number.runs, .keep_all = TRUE) 

ggplot(binpack_mads_log, aes(x=log_num_runs, y=median)) +
  geom_point(color="#E78AC3", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_abline(intercept = -3.72, slope = 1/3, color = "#666666") +
  labs(x = expression(paste(Log[2], " Number of Weights")),
       y = expression(paste("Median ", Log[2], " Empty Space"))) +
  scale_x_continuous(breaks = c(7,9,11,13,15,17)) +
  theme(panel.grid = element_blank()) 

```

<br><br>

```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.49** The logs of the mads for log empty space are graphed against log number of weights"}

ggplot(binpack_mads_log, aes(x=log_num_runs, y=log_mads)) +
  geom_point(color="#E78AC3", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = expression(paste(Log[2], " Number of Weights")),
       y = expression(paste(Log[2], " Mad of ", Log[2], " Empty Space"))) +
  scale_x_continuous(breaks = c(7,9,11,13,15,17)) +
  theme(panel.grid = element_blank()) 

```

<br><br>

```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.50** Log relative mads for log empty space are graphed against median log empty space"}

ggplot(binpack_mads_log, aes(x=median, y=relative_mads)) +
  geom_point(color="#E78AC3", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = expression(paste("Median ", Log[2], " Empty Space")),
       y = expression(paste(Log[2], " Relative Spread"))) +
  theme(panel.grid = element_blank()) 

```

<br><br>



```{r out.width="70%", out.height="70%", fig.cap="**Figure 2.51** Log relative mads for empty space are graphed against median empty space"}
bin.packing %>%
  group_by(number.runs) %>%
  mutate(median = median(empty.space),
         residual = empty.space - median,
         abs_residual = abs(residual),
         mads = median(abs_residual)) %>%
  ungroup() %>%
  mutate(min_mads = min(mads),
         relative_mads = log2(mads/min_mads)) %>%
  distinct(number.runs, .keep_all = TRUE) %>%
  ggplot(aes(x=median, y=relative_mads)) +
  geom_point(color="#E78AC3", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "Median Empty Space",
       y = expression(paste(Log[2], " Relative Spread"))) +
  scale_x_continuous(breaks = c(1.0, 1.7, 2.4, 3.1, 3.8)) +
  scale_y_continuous(breaks = c(0.0, 0.4, 0.8, 1.2)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r fig.height= 10, fig.width= 8, fig.cap="**Figure 2.52**  The outliers in the spread-standardized residuals have been removed. Direct manipulation provides a convenient environment for such point deletion"}
binpack_mads %>%
  filter(abs(spread_std_res) <= 4) %>%
  ggplot(aes(sample = spread_std_res)) +
  geom_qq(color = "#E78AC3") +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile", 
       y= expression(paste("Spread-Standardized Residual ", Log[2], " Empty Space"))) +
  facet_wrap(vars(number.runs), ncol = 3, as.table = FALSE) +
  scale_x_continuous(breaks = c(-2,0,2), limits = c(-2.2, 2.2)) +
  scale_y_continuous(breaks = c(-4,0,4), limits = c(-4.2, 4.2)) 
```

<br><br>



```{r}
mean_nv <- mean(fusion_fitted$log_time[fusion_fitted$nv.vv == "NV"])
mean_vv <- mean(fusion_fitted$log_time[fusion_fitted$nv.vv == "VV"])
n_nv <- nrow(fusion_fitted[fusion_fitted$nv.vv == "NV",])
n_vv <- nrow(fusion_fitted[fusion_fitted$nv.vv == "VV",])
t_stat <- 1.99

tot_res_sq <- 0
for (i in 1:nrow(fusion_fitted)) {
  tot_res_sq = tot_res_sq + (fusion_fitted$residual_ltime[i]^2)
}

sample_sd <- sqrt(tot_res_sq/76)
upper_ci <- (mean_nv - mean_vv) + t_stat*sample_sd*sqrt((1/n_nv) + (1/n_vv))
lower_ci <- (mean_nv - mean_vv) - t_stat*sample_sd*sqrt((1/n_nv) + (1/n_vv))
```



<br><br>

***

# **Chapter 3**   Bivariate Data

<br>

```{r out.width="70%", out.height="70%", fig.cap="**Figure 3.1** A scatterplot displays bivariate data: measurements of retinal area and CP ratio for 14 cat fetuses"}
ggplot(ganglion, aes(x = area, y =  cp.ratio)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "CP Ratio") +
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(3,18,3)) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r out.width="55%", fig.asp=1.08, fig.cap="**Figure 3.2** A loess curve has been added to the scatterplot of the ganglion data. The aspect ratio of the graph has been chosen to bank the curve to 45 degree"}
ggplot(ganglion, aes(x = area, y =  cp.ratio)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_smooth(method = "loess", color = "#A6D854", se = FALSE) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "CP Ratio") +
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(3,18,3)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="70%", out.height="70%", fig.cap="**Figure 3.4** The least-squares line has been added to the scatterplot of the ganglion data"}
ggplot(ganglion, aes(x = area, y =  cp.ratio)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_smooth(method = "lm", color = "#A6D854", se = FALSE) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "CP Ratio") +
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(3,18,3)) +
  theme(panel.grid = element_blank())
```

<br><br>

```{r out.width="55%", fig.asp=1.08, fig.cap="**Figure 3.5** The least-squares fit of a quadratic polynomial has been added to the scatterplot of the ganglion data. The curve is banked to 45 degree"}
ggplot(ganglion, aes(x = area, y =  cp.ratio)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), color = "#A6D854", se = FALSE) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "CP Ratio") +
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(3,18,3)) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r out.width="70%", fig.asp=0.55, fig.cap="**Figure 3.6** The data are fitted by loess. The curve is banked to 45 degree"}
x <- seq(5, 10, length.out=150)
z <- seq(0, 1, length.out=50)
y <- 5 + c(-(1-z)^.5, sin(z*2*pi), .5*z^2)
fit <- loess.smooth(x, y, degree = 2, family = "g", span = .5, evaluation = 150)
set.seed(20)
y <- fit$y + rnorm(150, 0, .2)
x <- fit$x

data_xy <- tibble(x,y)

ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_smooth(method = "loess", span = 0.35, color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())
```


<br><br>



```{r out.width="70%", fig.asp=1.6, fig.cap="**Figure 3.9** The three loess curves have three different values of the smoothing parameter, $\\alpha$. From the bottom panel to the top the values are 0.1, 0.3, and 0.6. The value of $\\lambda$ is 2."}

plot_1 <- ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 0.6,
              method.args = list(degree = 2),
              color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())


plot_2 <- ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 0.3,
              method.args = list(degree = 2),
              color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())


plot_3 <- ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 0.1,
              method.args = list(degree = 2),
              color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())

plot_grid(plot_1, plot_2, plot_3, ncol = 1)
```

<br><br>



```{r out.width="70%", fig.asp=1.6, fig.cap="**Figure 3.10** The three loess fits are shown. From the bottom panel to the top the parameters, $\\alpha$ and $\\lambda$, are the following: 0.1 and 1; 0.3 and 1; 0.3 and 2"}

plot_4 <- ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 0.3,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())


plot_5 <- ggplot(data_xy, aes(x,y)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 0.1,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  scale_y_continuous(breaks = seq(3.8, 5.8, 1)) +
  scale_x_continuous(breaks = seq(5,10,1)) +
  theme(panel.grid = element_blank())

plot_grid(plot_2, plot_4, plot_5, ncol=1)
```


<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.12** On this residual dependence plot, the residuals from the linear fit to CP ratio are graphed against area. The parameters of the loess curve on the plot are $\\alpha$ = 1 and $\\lambda$ = 1"}

ganglion_lm <- lm(cp.ratio~area, ganglion)

ganglion_res_lm <- tibble(ganglion$area, ganglion_lm$residuals)
ganglion_res_lm <- ganglion_res_lm %>%
  rename(area = "ganglion$area", residuals = "ganglion_lm$residuals")

ggplot(ganglion_res_lm, aes(x=area, y=residuals)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 1,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  scale_x_continuous(breaks = seq(20,140,40)) +
  scale_y_continuous(breaks = seq(-2,3,1)) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "Residual CP Ratio") +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.13** On this residual dependence plot, the residuals from the quadratic fit to CP ratio are graphed against area. The parameters of the loess curve on the plot are $\\alpha$ = 1 and $\\lambda$ = 1"}

ganglion_quadratic <- lm(cp.ratio~area + I(area^2), ganglion)
ganglion_res_quadratic <- tibble(ganglion$area, ganglion$cp.ratio, ganglion_quadratic$fitted.values, ganglion_quadratic$residuals)
ganglion_res_quadratic <- ganglion_res_quadratic %>%
  rename(area = "ganglion$area", cp.ratio = "ganglion$cp.ratio",
         fitted_values = "ganglion_quadratic$fitted.values",
         residuals = "ganglion_quadratic$residuals")

ggplot(ganglion_res_quadratic, aes(x=area, y=residuals)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 1,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  geom_hline(yintercept = 0, color="#666666") +
  scale_x_continuous(breaks = seq(20,140,40)) +
  scale_y_continuous(breaks = seq(-1.2,3,1.2)) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = "Residual CP Ratio") +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.14** On this s-l plot, the square root absolute residuals from the quadratic fit to CP ratio are graphed against the fitted values to check for monotone spread. The parameters of the loess curve on the plot are $\\alpha$ = 2 and $\\lambda$ = 1"}

ggplot(ganglion_res_quadratic, aes(x=fitted_values, y=sqrt(abs(residuals)))) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 2,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  labs(x = "Fitted CP Ratio",
       y = "Square Root Absolute Residual CP Ratio") +
  scale_x_continuous(breaks = seq(3,18,3)) +
  scale_y_continuous(breaks = seq(0.2, 1.0, 0.2)) +
  theme(panel.grid = element_blank())

```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.15** Log CP ratio is graphed against area. The curve is a loess fit with $\\alpha$ = 2/3 and $\\lambda$ = 1"}

ggplot(ganglion, aes(x=area, y=log2(cp.ratio))) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 2/3,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  labs(x = expression(paste("Area(", mm^2,")")),
       y = expression(paste(Log[2]," CP Ratio"))) + 
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(2,4,1)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.16** Log CP ratio is graphed against area. The curve is the least-squares fit"}
ggplot(ganglion, aes(x=area, y=log2(cp.ratio))) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = lm, color = "#A6D854", se = FALSE) +
  labs(x = expression(paste("Area(", mm^2,")")),
       y = expression(paste(Log[2]," CP Ratio"))) + 
  scale_x_continuous(breaks = seq(20, 140, 40)) +
  scale_y_continuous(breaks = seq(2,4,1)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.17** On this residual dependence plot, the residuals from the linear fit to log CP ratio are graphed against area. The parameters of the loess curve on the plot are $\\alpha = 1$ and $\\lambda$ = 1"}

ganglion_log <- lm(log2(cp.ratio) ~ area, ganglion)
ganglion_res_log <- tibble(ganglion$area, ganglion$cp.ratio, 
                                     ganglion_log$fitted.values, ganglion_log$residuals)

ganglion_res_log <- ganglion_res_log %>%
  rename(area = "ganglion$area", cp.ratio = "ganglion$cp.ratio",
         fitted_values = "ganglion_log$fitted.values",
         residuals = "ganglion_log$residuals")

ggplot(ganglion_res_log, aes(x=area, y=residuals)) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 1,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  geom_hline(yintercept = 0, color="#666666") +
  scale_x_continuous(breaks = seq(20,140,40)) +
  labs(x = expression(paste("Area (", mm^2,")")),
       y = expression(paste("Residual", Log[2], " CP Ratio"))) +
  theme(panel.grid = element_blank())

```


<br><br>


```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.18** An s-l plot for the linear fit to log CP ratio checks for monotone spread. The parameters of the loess curve are $\\alpha$ = 2 and $\\lambda$ = 1"}

ggplot(ganglion_res_log, aes(x=fitted_values, y=sqrt(abs(residuals)))) +
  geom_point(color = "#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_smooth(method = "loess", span = 2,
              method.args = list(degree = 1),
              color = "#A6D854", se = FALSE) +
  scale_x_continuous(breaks = seq(20,140,40)) +
  labs(x = expression(paste("Fitted ", Log[2]," CP Ratio")),
       y = expression(paste("Square Root Absolute Residual", Log[2], " CP Ratio"))) +
  theme(panel.grid = element_blank())

```

<br><br>



```{r out.width="70%", fig.asp=0.85, fig.cap="**Figure 3.19** An r-f spread plot compares the spreads of the residuals and the fitted values minus their mean for the linear fit to log CP ratio"}

ganglion_res_log %>%
  mutate("Fitted Values" = fitted_values - mean(fitted_values)) %>%
  rename(Residuals = residuals) %>%
  gather(key = "r_f", value = "values", -c(area, cp.ratio, fitted_values)) %>%
  ggplot(aes(sample = values)) +
  geom_qq(distribution = qunif, color="#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  facet_wrap(vars(r_f)) +
  labs(x = "f-value", 
       y=expression(paste(Log[2], " CP Ratio"))) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_y_continuous(breaks = seq(-1.2,1.8,0.6)) +
  theme(panel.spacing.x = unit(1,"lines"))

```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.20** A normal q-q plot compares the normal distribution with the distribution of the residuals for the linear fit to log CP ratio"}

ggplot(ganglion_log, aes(sample = .resid)) +
  geom_qq(color="#66A61E", size = 2.5, fill="white", shape=21, stroke=1) +
  stat_qq_line(color = "#666666") +
  labs(x = "Unit Normal Quantile", 
       y=expression(paste("Residual ", Log[2], " CP Ratio"))) +
  scale_x_continuous(breaks = seq(-2,2,1), limits = c(-2.1, 2.1)) +
  theme(panel.grid = element_blank())
```

<br><br>


```{r}
intercept <- ganglion_log$coefficients[1]
slope <- ganglion_log$coefficients[2]
range_area <- max(ganglion$area) - min(ganglion$area) # range of areas of the ganglion data
sd_res <- sd(ganglion_log$residuals) # sample standard deviation of the residuals

```


<br><br>


```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.21** The differences of carbon age and thorium age for 19 coral samples are graphed against the carbon ages"}

ggplot(dating, aes(x=carbon, y=(thorium - carbon))) +
  geom_point(color = "#E6AB02", size = 2.5, fill="white", shape=21, stroke=1) +
  labs(x = "Carbon Age (kry BP)",
       y = "Thorium Age - Carbon Age (kyr BP)") +
  scale_x_continuous(breaks = seq(6,24,6)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.22** The least-squares fit of a line has been added to the scatterplot of the dating data"}

ggplot(dating, aes(x=carbon, y=(thorium - carbon))) +
  geom_point(color = "#E6AB02", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_smooth(method = lm, se = FALSE, color = "#FFD92F") +
  labs(x = "Carbon Age (kry BP)",
       y = "Thorium Age - Carbon Age (kyr BP)") +
  scale_x_continuous(breaks = seq(6,24,6)) +
  theme(panel.grid = element_blank())

```

<br><br>

```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.23** The residuals from the least-squares fit to the dating data are graphed against carbon age"}

dating_lm <- lm((thorium - carbon) ~ carbon, dating)
dating_res_lm <- tibble(dating$carbon, dating_lm$residuals)
dating_res_lm <- dating_res_lm %>%
  rename(carbon = "dating$carbon", residuals = "dating_lm$residuals")

ggplot(dating_res_lm, aes(x=carbon, y= residuals)) +
  geom_point(color = "#E6AB02", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_hline(yintercept = 0, color = "#666666") +
  labs(x = "Carbon Age (kry BP)",
       y = "Residual Age Difference (kyr BP)") +
  scale_x_continuous(breaks = seq(6,24,6)) +
  theme(panel.grid = element_blank())
```

<br><br>



```{r out.width="50%", fig.asp=1, fig.cap="**Figure 3.25** The bisquare fit of a line has been added to the scatterplot of the dating data"}

ggplot(dating, aes(x = carbon, y = (thorium - carbon))) +
  geom_point(color = "#E6AB02", size = 2.5, fill="white", shape=21, stroke=1) +
  geom_smooth(method = MASS::rlm, se = FALSE,
              method.args = list(psi = "psi.bisquare"),
              color = "#FFD92F") +
  scale_x_continuous(breaks = seq(6,24,6)) +
  scale_y_continuous(breaks = seq(1,4,1)) +
  coord_cartesian(expand = FALSE, xlim = c(5.5,28), ylim = c(0.5,4.1)) +
  labs(x = "Carbon Age (kry BP)",
       y = "Thorium Age - Carbon Age (kyr BP)") +
  theme(panel.grid = element_blank())

```

